# Generated by Django 5.1.6 on 2025-02-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHCapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Joint', 'Joint')], max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.RenameField(
            model_name='formresponse',
            old_name='User_name',
            new_name='user_name',
        ),
        migrations.AlterField(
            model_name='formresponse',
            name='sender',
            field=models.EmailField(max_length=50),
        ),
    ]
