# Generated by Django 5.1.6 on 2025-02-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHCapp', '0002_serviceproviderresponse_delete_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderResponse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(choices=[('PHCs', 'PHCs'), ('Secondary Provider', 'Secondary Provider'), ('Tertiary Provider', 'Tertiary Provider')], max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
