# Generated by Django 5.1.6 on 2025-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UHCapp', '0003_serviceproviderresponse1'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empanelled', models.CharField(max_length=100)),
                ('access', models.CharField(max_length=100)),
                ('referred', models.CharField(max_length=100)),
                ('selection', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceProviderResponse1',
        ),
    ]
